service: api-gw-mapping

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1

custom:
  my_data: "My custom data"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: api-gw-sample-openapi-mapping
        # Carrega a definição da API a partir do arquivo openapi.yaml
        Body: ${file(openapi.yaml)}
